config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/user', to: 'user#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'foods#index'

  get '/public_recipes', to: 'public_recipes#index'
  get '/general_shopping_lists', to: 'general_shopping_lists#index'

  resources :foods
  resources :recipes do
    resources :recipe_foods
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 250 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user: current_user)
  end

  def show
    @recipes_show = Recipe.find(params[:id])
  end

  def destroy
    recipe_destroy = Recipe.find(params[:id])
    recipe_destroy.destroy
    flash[:notice] = 'Recipe succesfully deleted'
    redirect_to recipes_url
  end

  def new
    @recipe_new = current_user.recipe.new
    respond_to do |format|
      format.html { render :new, locals: { recipes: @recipe_new } }
    end
  end

  def create
    recipe_create = Recipe.new(params.require(:recipes).permit(:name, :preparation_time, :cooking_time, :description,
                                                               :public))
    recipe_create.update(user_id: current_user.id)

    respond_to do |format|
      format.html do
        if recipe_create.save
          flash[:success] = 'Recipe created successfully'
          redirect_to recipes_url
        else
          flash.now[:error] = 'Error: Recipe could not be created'

          render :new, locals: { recipes: @recipe_new }
        end
      end
    end
  end
end

app/views/recipes/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    
    <%= yield %>
    <div class="d-flex justify-content-around">
      <h2 class="h1 m-3">Recipes</h2>
      <a class="btn btn-secondary m-3" href="recipes/new">Add Recipe</a>
    </div>

    <div class="d-flex flex-column align-items-center">
      <% @recipes.each do |n| %>
        <div class="d-flex border border-secondary m-5 p-3 w-75" onclick="location.href='recipes/<%=n.id%>'">
          <div class="w-25">
            <p class="h5 m-3"><%=n.name%></p>
            <form action="/recipes/<%=n.id%>" method="post">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="hidden" name="_method" value="DELETE">
                <input type="submit" value="Delete" class="btn btn-secondary m-3">
              </form>
          </div>
          <div class="w-75">
            <p class="h5 m-3"><%=n.description%></p>
          </div>
        </div>
      <% end %>
    </div>
    
  </body>
</html>

app/views/recipes/new.html.erb
<h3 class="h3 m-3">Create a Recipe Form</h3>

<%= form_with model: @recipe_new, url: recipes_path, method: :post, class: "w-50 m-3", local: true, scope: :recipes do |f|  %>

  <div class = "form-group">
    <%= f.label :name, for: "names" %><br>
    <%= f.text_field :name, class: "form-control", id: "names"%>
  </div>

  <div class = "from-group">
    <%= f.label :preparation_time, for: "preparation"  %><br>
    <%= f.text_field :preparation_time,  class: "form-control", id: "preparation" %>
  </div>

  <div class = "from-group">
    <%= f.label :cooking_time, for: "cooking"  %><br>
    <%= f.text_field :cooking_time,  class: "form-control", id: "cooking" %>
  </div>

  <div class = "from-group">
    <%= f.label :description, for: "desc"  %><br>
    <%= f.text_area :description,  class: "form-control", id: "desc" %>
  </div>

  <div class = "form-check form-switch mb-3 pl-5 d-flex">
    <%= f.label :public, for: "flexSwitchCheckDefault", class: "form-check-label m-3" %><br>
    <%= f.check_box :public, class: "form-check-input m-3", id: "flexSwitchCheckDefault" %>
  </div>

  <%= f.submit "Create Recipe", class: "btn btn-secondary"%>
<% end %>

app/views/recipes/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= yield %>
    <div class="d-flex justify-content-center my-3"><h2 class="h1"><%=@recipes_show.name%></h2></div>

    <div class="d-flex justify-content-around m-3">
      <div>
        <p class="h3 mb-3">Preparation Time: <%=@recipes_show.preparation_time%></p>
        <p class="h3 mb-3">cooking Time: <%=@recipes_show.cooking_time%></p>
        <p class="h3 mb-3">Steps go here...</p>
      </div>
      <div class="form-check form-switch">
        <% if @recipes_show.public %>
          <input class="form-check-input" type="checkbox" id="flexSwitchCheck" checked>
          <label class="form-check-label" for="flexSwitchCheck">Public</label>
        <% else %>
          <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
          <label class="form-check-label" for="flexSwitchCheckDefault">Public</label>
        <% end %>
      </div>

    </div>

    <div class="d-flex justify-content-center">
      <div class="d-flex justify-content-around border-bottom border-3 w-75">
        <a class="btn btn-secondary m-3" href="/general_shopping_lists">Generate shopping list</a>
        <a class="btn btn-secondary m-3" href="<%=@recipes_show.id%>/recipe_foods/new">Add ingredient</a>
      </div>
    </div>

    <div class="d-flex justify-content-center">
      <table class="table table-striped w-75 m-3">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Value</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% RecipeFood.all.includes(:food).each do |n| %>
        <tr>
          <th scope="row"><%= n.food.name%></th>
          <td><%= n.quantity%></td>
          <td>₦<%=n.food.price%></td>
          <td class="d-flex">
            <a class="btn btn-secondary ">Modify</a>
            <form action="<%=@recipes_show.id%>/recipe_foods/<%= n.id%>" method="post" class="mx-3">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <input type="hidden" name="_method" value="DELETE">
              <input type="submit" value="Delete" class="btn btn-secondary">
            </form>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    
  </body>
</html>