config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/user', to: 'user#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'foods#index'

  get '/public_recipes', to: 'public_recipes#index'
  get '/general_shopping_lists', to: 'general_shopping_lists#index'

  resources :foods
  resources :recipes do
    resources :recipe_foods
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :inventory_food
  has_many :recipe_food

  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # before_action :authenticate_user!
  def index
    @foods = Food.all
  end

  def new
    @food_new = current_user.food.new
    respond_to do |format|
      format.html { render :new, locals: { foods: @food_new } }
    end
  end

  def create
    food_create = Food.new(params.require(:foods).permit(:name, :measurement_unit, :price))
    food_create.update(user_id: current_user.id)

    respond_to do |format|
      format.html do
        if food_create.save
          flash[:success] = 'Food created successfully'
          redirect_to foods_url
        else
          flash.now[:error] = 'Error: Food could not be created'

          render :new, locals: { foods: @food_new }
        end
      end
    end
  end

  def destroy
    food_destroy = Food.find(params[:id])
    food_destroy.destroy
    flash[:notice] = 'Food succesfully deleted'
    redirect_to foods_url
  end
end

app/views/foods/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= yield %>
    <a class="btn btn-secondary m-3" href="foods/new">Add Food</a>
    <table class="table table-striped w-75 m-3">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Food</th>
          <th scope="col">Measurement Unit</th>
          <th scope="col">Unit price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each_with_index do |n, idx| %>
        <tr>
          <th scope="row"><%=idx + 1%></th>
          <td><%= n.name%></td>
          <td><%= n.measurement_unit%></td>
          <td>₦<%=n.price%></td>
          <td>
            <%if n.user_id == current_user.id%>
              <form action="/foods/<%=n.id%>" method="post">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="hidden" name="_method" value="DELETE">
                <input type="submit" value="Delete" class="btn btn-secondary">
              </form>
            <%end%>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </body>
</html>

app/views/foods/new.html.erb
<h3 class="h3 m-3">Create a Food Form</h3>

<%= form_with model: @food_new, url: foods_path, method: :post, class: "w-50 m-3", local: true, scope: :foods do |f|  %>

  <div class = "form-group">
    <%= f.label :name, for: "names" %><br>
    <%= f.text_field :name, class: "form-control", id: "names"%>
  </div>
  <div class = "from-group">
    <%= f.label :measurement_unit, for: "measures"  %><br>
    <%= f.text_field :measurement_unit,  class: "form-control", id: "measures" %>
  </div>

  <div class = "form-group mb-3">
    <%= f.label :price, for: "prices" %><br>
    <%= f.text_field :price, class: "form-control", id: "prices" %>
  </div>

  <%= f.submit "Send Post", class: "btn btn-secondary"%>
<% end %>