config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/user', to: 'user#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'foods#index'

  get '/public_recipes', to: 'public_recipes#index'
  get '/general_shopping_lists', to: 'general_shopping_lists#index'

  resources :foods
  resources :recipes do
    resources :recipe_foods
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  def self.pricer(reci)
    var = 0
    RecipeFood.where(recipe: reci).each do |n|
      var += n.food.price
    end
    var
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    puts "All this just to make you stand out in the rain#{params}"
    @recipe_food = RecipeFood.new
    respond_to do |format|
      format.html { render :new, locals: { recipe_foods: @recipe_food } }
    end
  end

  def create
    recipe_food_create = RecipeFood.new(params.require(:recipe_foods).permit(:quantity, :food_id))
    recipe_food_create.update(recipe_id: params[:recipe_id])

    respond_to do |format|
      format.html do
        if recipe_food_create.save
          flash[:success] = 'Ingredient created successfully'
          redirect_to "/recipes/#{params[:recipe_id]}"
        else
          flash.now[:error] = 'Error: Ingredient could not be created'
          render :new, locals: { recipe_foods: @recipe_food }
        end
      end
    end
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])
    recipe_food.destroy
    redirect_to "/recipes/#{params[:recipe_id]}"
  end
end

app/views/recipe_foods/new.html.erb
<h3 class="h3 m-3">Create a Food Form</h3>
<div class="d-flex"> 
  <%= form_with model: @recipe_food, url: recipe_recipe_foods_path, method: :post, class: "w-50 m-3", local: true, scope: :recipe_foods do |f|  %>

    <div class = "from-group">
      <%= f.label :quantity, for: "quat"  %><br>
      <%= f.text_field :quantity,  class: "form-control", id: "quat" %>
    </div>

    <div class = "form-group mb-3">
      <%= f.label "Food ID", for: "foodsid" %><br>
      <%= f.text_field :food_id, class: "form-control", id: "foodsid" %>
    </div>

    <%= f.submit "Add Ingredient", class: "btn btn-secondary"%>
  <% end %>
  <div>
    <table class="table table-striped w-50 h-50">
      <thead>
        <tr>
          <th scope="col">Food ID</th>
          <th scope="col">Food</th>
          <th scope="col">Measurement Unit</th>
          <th scope="col">Unit price</th>
        </tr>
      </thead>
      <tbody>
        <% Food.all.each do |n| %>
        <tr>
          <th scope="row">ID: <%=n.id%></th>
          <td><%= n.name%></td>
          <td><%= n.measurement_unit%></td>
          <td>₦<%=n.price%></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>